/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ROD-Logo/ROD_Logo.gltf -t -r public 
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }

}

export function LogoModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ROD-Logo/ROD_Logo.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} scale={5}>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ROD-Logo/ROD_Logo.gltf')
